# Generated by Django 5.1.4 on 2025-01-26 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_rename_status_task_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='assign_to',
            new_name='assigned_to',
        ),
    ]
