# Generated by Django 5.1.4 on 2025-01-30 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_project_description_alter_task_assigned_to_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskdetail',
            name='assigned_to',
        ),
    ]
