# Generated by Django 5.1.4 on 2025-02-13 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_task_assigned_to'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
