# Generated by Django 5.1.4 on 2025-02-13 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_delete_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskdetail',
            name='asset',
            field=models.ImageField(blank=True, null=True, upload_to='tasks_asset'),
        ),
    ]
